### ISSUE TITLE
Create a TODO List 

### ISSUE THREAD

**Issue by aswinkumar1999** [CleanPegasus/TensorDash#10]
Hey @CleanPegasus, This project seems really cool, would like to contribute. 

I created a PR  ( #9 )  but that was something I felt could be done so as to not expose my password. 

If you guys have a TODO list adding that to the README would help people contribute to the Repo. 

Some things I can currently think of are : 

- [ ] Multiple-Model Training using Single Sign-In
- [ ] Status shows running when Training is forcefully terminated before completion.
- [ ] Allow Models with the Same Name and Include Timestamps to differentiate them.

**Comment by aswinkumar1999** [comment]
And also Stuff like Support for Wear OS and Android Auto.

**Comment by CleanPegasus** [comment]
Hey! Sorry we didn't get time to review the PR. We still have a few things in mind. We'll finish those up and add a #TODO list to the README.
Thanks.
